### ISSUE TITLE
addDays does not work correctly for negative numbers

### ISSUE THREAD

**Issue by dg76** [dnfield/dart_calendar#8]
Hi!

GregorianCalendar(2019,8,30).addDays(1) is 2019-08-31

but

GregorianCalendar(2019,9,2).addDays(-2) is 2019-08-30

and

GregorianCalendar(2019,9,2).addDays(-1) is 2019-09-01

So August 31 seems to be completely missing.

**Comment by dg76** [comment]
I think I have fixed it now: #9

**Comment by dnfield** [comment]
Fixed by #9
